default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graphql_react_boilerplate_development
  port: 5432

test:
  <<: *default
  database: graphql_react_boilerplate_test

production:
  <<: *default
  database: graphql_react_boilerplate_production
  username: graphql_react_boilerplate
  password: <%= ENV["GRAPHQL_REACT_BOILERPLATE_DATABASE_PASSWORD"] %>
